CREATE TABLE "prayer_times" (
	"id" bigint PRIMARY KEY NOT NULL,
	"city" integer NOT NULL,
	"date_text_cyrl" text NOT NULL,
	"date_text_uz" text NOT NULL,
	"tong" varchar(5) NOT NULL,
	"quyosh" varchar(5) NOT NULL,
	"peshin" varchar(5) NOT NULL,
	"asr" varchar(5) NOT NULL,
	"shom" varchar(5) NOT NULL,
	"xufton" varchar(5) NOT NULL,
	"updated_date" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "prayer_time_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prayer_time_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 6000 CACHE 1),
	"tg_id" varchar(255),
	"first_name" text,
	"last_name" text,
	"username" text,
	"city" integer,
	"language" integer,
	"time" integer,
	"is_active" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "prayer_times_city_key" ON "prayer_times" USING btree ("city");--> statement-breakpoint
CREATE INDEX "idx_prayer_times_region_date" ON "prayer_times" USING btree ("city");--> statement-breakpoint
CREATE UNIQUE INDEX "users_namoz_vaqtlari_bot_tg_id_unique" ON "prayer_time_users" USING btree ("tg_id");